import React from 'react'
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
import Card from './Card';

const responsive = {
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3,
      slidesToSlide: 3 // optional, default to 1.
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
      slidesToSlide: 2 // optional, default to 1.
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
      slidesToSlide: 1 // optional, default to 1.
    }
  };

  const cardData = [{
    title:"What is it ?",
    text:"A wireless printer is a printer with Wi-Fi that communicates with other wireless devices. This can be achieved either through technologies such as Wi-Fi, which uses radio waves, or Bluetooth, which uses a Personal Area Network (PAN). Using a wireless printer lets you share it over multiple devices, without having to run multiple cables to it. a Wi-Fi printer can connect to your internet router, as well as devices such as your smartphone themselves. The main idea of developing this IoT Based Wireless Cloud Printer System is to provide a fast secure solution and also to clean up and maximize the workspace along with the time saving property. Individual RFID Tag with the UID will impart a secure printing process."
  },{
    title:"Use Cases",
    text: " It can be used at homes,universities,corporate offices by converting conventional wired printers into smart wireless printers at extremely low cost , thus saving both money and e-waste. It can build potential business by replacing printing and photocopying shops with a completely automated standalone system without human intervention. It covers the disadvantages of local printing shops by providing better security and minimizing waiting period."
  },
{
  title:"Tech Stack",
  text:"Raspberry Pi is used as the main CPU to process the user inputs and fetch documents from cloud and send it to the printer. Google Firebase is used as the backend for user interface and also used as a cloud database to securely store the documents. React JS is the frontend javascript framework used to design user interface and take input and send it to the cloud database. RFID/QR can be used to authenticate/identify each user uniquely."
},
{
  title:"Benefits",
  text:"Personal Printers are being manufactured with the sole purpose of keeping the buying price low.This initial cost cutting is offset by expensive cartridges and higher price per page. On the other hand, the end user does not wish to spend any extra money than those budget printers simply because the user doesn’t feel comfortable spending extra. The device is expected to reduce the reliance on personal printers. The added convenience will divert a huge user base to use commercial printers on a larger scale which will indirectly reduce the E-Waste generated by manufacturing the said “Home Use” printers. Reduction in E waste will help towards environment conservation in a positive way."
}]


function ImageCarousel() {
  return (
    <>
        <Carousel responsive={responsive} infinite={true}>
  <div><Card title={cardData[0].title} text={cardData[0].text}/></div>
  <div><Card title={cardData[1].title} text={cardData[1].text}/></div>
  <div><Card title={cardData[3].title} text={cardData[3].text}/></div>
  <div><Card title={cardData[2].title} text={cardData[2].text}/></div>
</Carousel>;


    </>
  )
}

export default ImageCarousel